import mobile from "../EcommeraceModule/StoreAssets/img/mobile2.jpg";
import laptop from "../EcommeraceModule/StoreAssets/img/laptop2.jpg";
// import watch from "../EcommeraceModule/StoreAssets/img/watch2.jpg";
// import speaker from "../EcommeraceModule/StoreAssets/img/Speaker2.jpg";
import SP1 from "../EcommeraceModule/StoreAssets/img/SpecialProduct1/SP1.jpg";
import SP2 from "../EcommeraceModule/StoreAssets/img/SpecialProduct1/SP2.jpg";
import SP3 from "../EcommeraceModule/StoreAssets/img/SpecialProduct1/SP3.jpg";
// import SP4 from "../../EcommeraceModule/StoreAssets/img/SpecialProduct1.jpg";
import sp1 from "../EcommeraceModule/StoreAssets/img/SpecialProduct2/sp1.jpg";
import sp2 from "../EcommeraceModule/StoreAssets/img/SpecialProduct2/sp2.jpg";
import sp3 from "../EcommeraceModule/StoreAssets/img/SpecialProduct2/sp3.jpg";

import camera from "../EcommeraceModule/StoreAssets/img/camers.jpg";
import headphone from "../EcommeraceModule/StoreAssets/img/headphone1.jpg";
import speaker from "../EcommeraceModule/StoreAssets/img/speaker.jpg";
import tab from "../EcommeraceModule/StoreAssets/images/tab.jpg";
import watch from "../EcommeraceModule/StoreAssets/images/watch.jpg";
import cameraHovered from "../EcommeraceModule/StoreAssets/img/CameraHovered.jpg";
import headphonehover from "../EcommeraceModule/StoreAssets/img/headphonehover.jpg";
import speakerhover from "../EcommeraceModule/StoreAssets/img/speakerhover.jpg";
import tabhover from "../EcommeraceModule/StoreAssets/images/tab1.jpg";
import watchhover from "../EcommeraceModule/StoreAssets/img/watchhovered.jpg";

export const products = [
  {
    id: 1,
    category: 0,
    price: "$100.00",
    heading: "Olympus pen, EZ lens",
    brand: "Havells",
    productCardImage: camera,
    imageonHover: cameraHovered,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 4, review: "Very Nice" },
      { stars: 4, review: "Very Beautiful Products" },
      { stars: 4, review: "Recomended" },
    ],
  },
  {
    id: 2,
    productCardImage: headphone,
    heading: "Headphones for Kids",
    brand: "Havells",
    price: "$500",
    imageonHover: headphonehover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 4, review: "Very Good Products" },
      { stars: 4, review: "Very Nice" },
      { stars: 4, review: "Very Beautiful Products" },
      { stars: 4, review: "Recomended" },
    ],
  },
  {
    id: 3,
    productCardImage: speaker,
    heading: "Portable Speakers",
    brand: "Bajaj",
    price: "$200",
    imageonHover: speakerhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 3, review: "Very Good Products" },
      { stars: 3, review: "Very Nice" },
      { stars: 3, review: "Very Beautiful Products" },
      { stars: 3, review: "Recomended" },
    ],
  },
  {
    id: 4,
    productCardImage: tab,
    heading: "Tab from Havells",
    brand: "Havells",
    price: "$200",
    imageonHover: tabhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Recomended" },
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Beautiful Products" },
    ],
  },
  {
    id: 5,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "$200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 4, review: "Very Good Products" },
      { stars: 4, review: "Very Nice" },
      { stars: 4, review: "Very Beautiful Products" },
      { stars: 4, review: "Recomended" },
    ],
  },
  {
    id: 6,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Havells",
    price: "$250.00",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Smart Watch with Advanced Health Monitoring, Fitness Tracking",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 7,
    productCardImage: mobile,
    heading: "Mobile from Havells",
    brand: "Havells",
    price: "$30",
    imageonHover: mobilehover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["speaker", "vivo", "mobile", "wire"],
    name: "Samsung Galaxy A23 128GB 6GB RAM Purple Color",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 8,
    productCardImage: Webcam,
    heading: "Webcam from Bajaj",
    brand: "Bajaj",
    price: "$20.00",
    imageonHover: Webcamhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["oppo", "vivo", "speaker", "wire"],
    name: "New Upgraded 2K 1080P Streaming Webcam with Ring Light",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 9,
    productCardImage: laptop,
    heading: "Laptop from Bajaj",
    brand: "Bajaj",
    price: "$60.00",
    imageonHover: laptophover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "wire"],
    name: "HD Resolution Indoor Wi-Fi Security Camera, White",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 10,
    productCardImage: camera,
    heading: "Camera from Sony",
    brand: "Sony",
    price: "$20.00",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["camera", "oppo", "wire", "mobile"],
    name: "JBL Link Music Bluetooth Lautsprecher, Brown",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 11,
    productCardImage: tablet,
    heading: "Tablet from Havells",
    brand: "Havells",
    price: "$26.00",
    imageonHover: tablethover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["mobile", "oppo", "speaker", "tablet"],
    name: "BoAt Rockerz 400 Bluetooth Headset Pink",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 12,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "$10.00",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "wire", "tablet"],
    name: "Milanese Loop Watch Band for 42mm/44mm Apple Watch ",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 13,
    productCardImage: camera,
    heading: "Camera from Bajaj",
    brand: "Bajaj",
    price: "$200",
    imageonHover: camerahover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["camera", "oppo", "speaker", "tablet"],
    name: "Hero Session Action Camera with 8MP Photos",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 14,
    productCardImage: speaker,
    heading: "Speaker from Bajaj",
    brand: "Bajaj",
    price: "$220.00",
    imageonHover: speakerhoverhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "headphone"],
    name: "Sony EXTRA BASS Portable Splash-proof Wireless Speaker",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 15,
    productCardImage: headphone,
    heading: "Headphone from Sony",
    brand: "Sony",
    price: "$41.00",
    imageonHover: headphonehover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["Headphone", "oppo", "speaker", "tablet"],
    name: "Bang & Olufsen Beoplay H9i Wireless Over-Ear Headphones",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 16,
    productCardImage: laptop,
    heading: "Laptop from Bajaj",
    brand: "Bajaj",
    price: "$150",
    imageonHover: laptophover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "headphone", "speaker", "tablet"],
    name: "Apple MacBook Air Laptop: M1 chip, 13.3-inch/33.74 cm",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 17,
    productCardImage: headphone,
    heading: "Headphone from Bajaj",
    brand: "Bajaj",
    price: "$100",
    imageonHover: headphonehover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["headphone", "oppo", "speaker", "tablet"],
    name: "Apple AirPods Max 2020 with Smart Case – Blue",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 18,
    productCardImage: tv,
    heading: "Monitor from Bajaj",
    brand: "Baja",
    price: "$200",
    imageonHover: tvhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "tv", "led", "monitor"],
    name: "Dell S27QC 27 inch 4K UHD Monitor – Grey",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 19,
    productCardImage: mobile,
    heading: "Mobile from Sony",
    brand: "Sony",
    price: "$30.00",
    imageonHover: mobilehover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["mobile", "oppo", "phone", "tablet"],
    name: "Smart Watch for Android iPhone, Bluetooth Phone Calls",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 20,
    productCardImage: tablet,
    heading: "Tablet from Sony",
    brand: "Sony",
    price: "$11.00",
    imageonHover: tablethover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["tablet", "oppo", "mobile", "vivo"],
    name: "Samsung Galaxy Tab A SM-T295, 4G Factory Unlocked",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 21,
    productCardImage: mobile,
    heading: "Mobile from Havells",
    brand: "Havells",
    price: "$200",
    imageonHover: mobilehover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "mobile", "tablet"],
    name: "Samsung Galaxy Note10+ Mobile Phone; Sim Free Smartphone",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 22,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "$200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 23,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "$200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 24,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "$200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 25,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "$200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 26,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "$200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 27,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "$200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 28,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "$200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 29,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "$200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 30,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "$200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 31,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "$200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
];
